# Generated by Django 5.0.4 on 2024-06-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenpageapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='women_poster_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_img', models.CharField(max_length=50)),
            ],
        ),
    ]
