# Generated by Django 5.0.4 on 2024-06-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenpageapp', '0003_women_product_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='women_product_carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.CharField(max_length=50)),
                ('product_title', models.CharField(max_length=50)),
                ('product_des', models.TextField(max_length=200)),
                ('product_price', models.CharField(max_length=50)),
            ],
        ),
    ]
