# Generated by Django 5.0.4 on 2024-06-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenpageapp', '0004_women_product_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='women_bottom_poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottom_img', models.CharField(max_length=50)),
            ],
        ),
    ]
